clc
path_Sequential='/Users/evatakou/Documents/MATLAB/Defect_Nuclear_GHZ_states/GHZ_states_Preparation/Simulations/GHZ_Data_of_Sequential_NEW/GHZ4_Sequential.mat';
path_Multispin ='/Users/evatakou/Documents/MATLAB/Defect_Nuclear_GHZ_states/GHZ_states_Preparation/Simulations/GHZ_Data_of_MultiSpin_NEW/GHZ4_Multispin.mat';
%unitary_vs_non_unitary_MwayEP(path_Sequential,path_Multispin)
unitary_vs_non_unitary_MwayEP_Analytical(path_Sequential,path_Multispin)